commit

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -3,7 +3,7 @@ name: Lint Python Code
 on: [pull_request]
 
 jobs:
-  lint_flake8:
+  format_ruff:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -12,18 +12,17 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
-          python-version: '3.x'
+          python-version: "3.x"
 
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install flake8>=3.8.0
+          pip install ruff
 
-      - name: Run flake8
+      - name: Run ruff format
         run: |
-          flake8 .
-
-  lint_black:
+          ruff format --check || exit 1
+  lint_ruff:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -32,13 +31,13 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
-          python-version: '3.x'
+          python-version: "3.x"
 
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install black
+          pip install ruff
 
-      - name: Run black
+      - name: Run ruff lint
         run: |
-          black --check .
+          ruff check . || exit 1  # Fail the job if ruff finds any issues
