Update lint workflow for ruff checks

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -1,3 +1,5 @@
+name: Lint Python Code
+
 on: [pull_request]
 
 jobs:
@@ -6,34 +8,30 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
-
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
           python-version: "3.x"
-
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install ruff
       - name: Run ruff format
         run: |
-          ruff format || exit 1
+          ruff format --check || exit 1
   lint_ruff:
     runs-on: ubuntu-latest
-    steps:
+    steps:  
       - name: Checkout code
         uses: actions/checkout@v2
-
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
           python-version: "3.x"
-
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install ruff
       - name: Run ruff lint
         run: |
-          ruff check || exit 1  # Fail the job if ruff finds any issues
+          ruff check . || exit 1  # Fail the job if ruff finds any issues
