commit

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -1,5 +1,5 @@
 name: Validate PR
-description: "Validate pull requests for naming conventions, linked issues, and version bumps"
+description: "Validate pull requests for code conventions, naming conventions, linked issues, and version bumps"
 
 on:
     pull_request:
@@ -7,8 +7,49 @@ on:
         types: [opened, edited, synchronize, ready_for_review]
 
 jobs:
+    format_ruff:
+        name: Code Formatted
+        runs-on: ubuntu-latest
+        steps:
+            - name: Checkout code
+              uses: actions/checkout@v2
+
+            - name: Set up Python
+              uses: actions/setup-python@v2
+              with:
+                  python-version: "3.x"
+
+            - name: Install dependencies
+              run: |
+                  python -m pip install --upgrade pip
+                  pip install ruff
+
+            - name: Run ruff format
+              run: |
+                  ruff format || exit 1
+    lint_ruff:
+        name: Code Linted
+        runs-on: ubuntu-latest
+        steps:
+            - name: Checkout code
+              uses: actions/checkout@v2
+
+            - name: Set up Python
+              uses: actions/setup-python@v2
+              with:
+                  python-version: "3.x"
+
+            - name: Install dependencies
+              run: |
+                  python -m pip install --upgrade pip
+                  pip install ruff
+
+            - name: Run ruff lint
+              run: |
+                  ruff check || exit 1  # Fail the job if ruff finds any issues
+
     validate-linked-issue:
-        name: Validate Linked Issue
+        name: Issue Linked
         runs-on: ubuntu-latest
         permissions:
             pull-requests: read
@@ -150,7 +191,7 @@ jobs:
 
                       console.log('✅ Pull request is properly linked to an issue.');
     validate-version-bump:
-        name: Validate Version Bump
+        name: Version Bump
         runs-on: ubuntu-latest
         steps:
             - name: Checkout code
